# ------------------------------------------------------------------------------------
# Developed by Carpathian, LLC.
# ------------------------------------------------------------------------------------
# Legal Notice: Distribution Not Authorized.
# ------------------------------------------------------------------------------------
# Notes:
# - byte-level repetition control shared by both decode backends. two mechanisms
#   over a sliding window of the last rep_window generated bytes:
#     1. no-repeat-ngram (hard ban): a candidate byte that would complete an
#        n-byte sequence already emitted verbatim is masked out (-inf). blocks
#        verbatim phrase loops. n ~ 16-24 bytes at byte level.
#     2. suffix-repeat penalty (soft): a byte that extends the current longest
#        verbatim suffix run is demoted by penalty * (run - min_match + 1) nats,
#        so the demotion factor exp(-p) is scale-free and identical across the
#        pytorch and c samplers. discourages building toward a loop.
# - penalizing raw bytes is too crude at byte level (every byte recurs); both
#   mechanisms key on multi-byte verbatim runs instead. off unless enabled.
# - the c engine sampler (model.c::sample_token_ext) mirrors this algorithm and
#   constants byte-for-byte; keep the two in sync.
# veritate_mri/inference/decode/repetition.py
# ------------------------------------------------------------------------------------
# Imports:

import numpy as np

# ------------------------------------------------------------------------------------
# Constants

REP_WINDOW_DEFAULT      = 256
REP_PENALTY_DEFAULT     = 0.5
NO_REPEAT_NGRAM_DEFAULT = 16
REP_MIN_MATCH           = 4
REP_MATCH_CAP           = 64

# ------------------------------------------------------------------------------------
# Functions


class RepetitionController:
    """Per-stream repetition state. observe() every emitted byte; compute()
    returns (ban_mask, soft) to apply to the current-step logits, or (None,
    None) when disabled or no penalty applies."""

    def __init__(self, vocab, rep_window=0, rep_penalty=0.0, no_repeat_ngram=0):
        self.vocab = int(vocab)
        self.window = int(rep_window)
        self.penalty = float(rep_penalty)
        self.ngram = int(no_repeat_ngram)
        self.enabled = self.penalty > 0.0 or self.ngram > 0
        self.hist = []

    def observe(self, byte):
        if self.enabled:
            self.hist.append(int(byte) & 0xff)

    def compute(self):
        if not self.enabled or not self.hist:
            return None, None
        h = self.hist
        n = len(h)
        win = self.window if self.window > 0 else n
        lo = n - win if n > win else 0
        w = h[lo:]
        t = len(w)
        best = [-1] * 256
        for i in range(t):
            length = 0
            while (length < REP_MATCH_CAP and (i - 1 - length) >= 0
                   and w[i - 1 - length] == w[t - 1 - length]):
                length += 1
            bv = w[i]
            if length > best[bv]:
                best[bv] = length
        ban = None
        soft = None
        for bv in range(256):
            length = best[bv]
            if length < 0:
                continue
            run = length + 1
            if self.ngram > 0 and run >= self.ngram:
                if ban is None:
                    ban = np.zeros(self.vocab, dtype=bool)
                ban[bv] = True
            elif self.penalty > 0.0 and run >= REP_MIN_MATCH:
                if soft is None:
                    soft = np.zeros(self.vocab, dtype=np.float32)
                soft[bv] = self.penalty * (run - REP_MIN_MATCH + 1)
        return ban, soft
