# ------------------------------------------------------------------------------------
# Developed by Carpathian, LLC.
# ------------------------------------------------------------------------------------
# Legal Notice: Distribution Not Authorized.
# ------------------------------------------------------------------------------------
# Notes:
# - Builds the code byte-level corpora (python, javascript, html, css, coding Q&A,
#   and the mixed_code experimental variants) shipped to Mirach-Corpuses.
# - Two phases. `stage` pulls source documents to a local jsonl cache (network);
#   `build` assembles bins from the cache (offline, deterministic from a seed).
# - Sources, all pinned to fixed revisions so rebuilds are byte-identical:
#     py/js: HuggingFaceTB/stack-edu metadata (education-classifier scored), file
#            content fetched anonymously from the public Software Heritage S3.
#     html/css: curated permissive-license GitHub repos, tarballs by pinned ref.
#     qa: donfu/oa-stackexchange, stackoverflow rows filtered to coding tags and
#         vote thresholds, framed as ChatML per documentation.md (corpus framing).
# - Code families emit autocomplete mode: raw files joined by <|endoftext|>.
#   qa emits chat mode (ChatML). Val split is a stable 2% hash bucket per doc.
# - mixed_* build variants for the corpus-style ablation:
#     mixed_raw   size caps + exact dedup only (control)
#     mixed_files full filters + near-dedup, score>=3
#     mixed_edu   full filters + near-dedup, score>=4 (textbook tier)
#     mixed_qa    mixed_files pool 50% + Q&A 50%
# - Run:
#     python veritate_mri/tools/build_code_corpus.py stage --family py --target-mb 1300
#     python veritate_mri/tools/build_code_corpus.py build --family py \
#       --out-train py_code_1gb_train.bin --out-val py_code_1gb_val.bin --target-mb 1000
# veritate_mri/tools/build_code_corpus.py
# ------------------------------------------------------------------------------------
# Imports:

import argparse
import ast
import gzip
import hashlib
import io
import json
import os
import random
import sys
import tarfile
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests

# ------------------------------------------------------------------------------------
# Constants

STACK_EDU_ID       = "HuggingFaceTB/stack-edu"
STACK_EDU_REVISION = "eeec5caac5cc3758a18f1d3ba4416837a9ba814c"
STACK_EDU_CONFIGS  = {"py": "Python", "js": "JavaScript"}
SWH_URL            = "https://softwareheritage.s3.amazonaws.com/content/{blob_id}"
SWH_WORKERS        = 64
SWH_RETRIES        = 3

QA_ID       = "donfu/oa-stackexchange"
QA_REVISION = "ae54b00b7c688866e86acf4605034ed2bded75f3"
QA_SOURCES  = {"stackexchange-stackoverflow", "stackoverflow"}
QA_TAGS     = {"python", "javascript", "html", "css", "jquery", "node.js", "reactjs",
               "typescript", "django", "flask", "pandas", "numpy", "dom", "webpack"}
QA_MIN_ANSWER_SCORE   = 5
QA_MIN_QUESTION_SCORE = 2
QA_MIN_CHARS = 30
QA_MAX_CHARS = 6000

REPOS = [
    ("mdn/learning-area",                        "180371ffc567f0f2ef359bf408b976667839e764"),
    ("mdn/dom-examples",                         "5419e769b8cae4f94e6634668cdaa3c33b0127cb"),
    ("web-platform-tests/wpt",                   "82e703d8ad0f5e132c1609743989df73f2b95aae"),
    ("twbs/bootstrap",                           "v5.3.3"),
    ("h5bp/html5-boilerplate",                   "v9.0.1"),
    ("picocss/pico",                             "v2.0.6"),
    ("jgthms/bulma",                             "1.0.1"),
    ("necolas/normalize.css",                    "8.0.1"),
    ("animate-css/animate.css",                  "v4.1.1"),
    ("sindresorhus/github-markdown-css",         "v5.6.1"),
    ("tobiasahlin/SpinKit",                      "v2.0.1"),
    ("nostalgic-css/NES.css",                    "v2.3.0"),
    ("google/material-design-lite",              "v1.3.0"),
    ("StartBootstrap/startbootstrap-creative",   "v7.0.7"),
    ("StartBootstrap/startbootstrap-agency",     "v7.0.12"),
    ("StartBootstrap/startbootstrap-clean-blog", "v6.0.9"),
    ("StartBootstrap/startbootstrap-grayscale",  "v7.0.6"),
    ("StartBootstrap/startbootstrap-freelancer", "v7.0.7"),
    ("StartBootstrap/startbootstrap-resume",     "v7.0.6"),
    ("StartBootstrap/startbootstrap-sb-admin-2", "v4.1.4"),
]
CODELOAD_URL   = "https://codeload.github.com/{repo}/tar.gz/{ref}"
REPO_BYTE_CAPS = {"web-platform-tests/wpt": 150 * 1024 * 1024}

MIN_DOC_BYTES = {"py": 256, "js": 256, "html": 512, "css": 256}
MAX_DOC_BYTES = {"py": 100_000, "js": 100_000, "html": 150_000, "css": 100_000}
MEAN_LINE_CAP = {"py": 120, "js": 160, "html": 300, "css": 200}

STAGE_MIN_SCORE   = 3
BUILD_MIN_SCORE   = 4
AUTOGEN_MARKERS   = ("do not edit", "auto-generated", "autogenerated", "@generated",
                     "generated by", "this file was generated")
JS_BUNDLE_MARKERS = ("webpackbootstrap", "sourcemappingurl", "/*! for license",
                     "!function(", "parcelrequire")
JS_KEYWORDS       = ("function", "=>", "const ", "let ", "var ", "class ")
HTML_MARKERS      = ("<!doctype", "<html", "<body", "<div", "<section", "<head")

SIMHASH_BANDS   = 4
SIMHASH_HAMMING = 3

IM_START = "<|im_start|>"
IM_END   = "<|im_end|>"
EOT      = "<|endoftext|>"

VAL_BUCKETS     = 50      # 1 in 50 docs -> val (2%)
DEFAULT_SEED    = 20260715
DEFAULT_STAGING = os.path.expanduser("~/.cache/veritate/code_corpus_staging")
TEXTBOOK_CACHE  = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                                "..", "..", "trainers", "corpus",
                                                "_code_textbook_cache"))

MIXED_WEIGHTS  = {"py": 0.40, "js": 0.40, "html": 0.10, "css": 0.10}
MIXED_QA_SHARE = 0.5
CODE_FAMILIES  = ("py", "js", "html", "css")
MIXED_VARIANTS = ("mixed_raw", "mixed_files", "mixed_edu", "mixed_qa")

HTTP_TIMEOUT = 60

# ------------------------------------------------------------------------------------
# Functions

_tls = threading.local()


def _session():
    if not hasattr(_tls, "s"):
        _tls.s = requests.Session()
    return _tls.s


def _http_get(url, timeout=HTTP_TIMEOUT, retries=SWH_RETRIES):
    last = None
    for _ in range(retries):
        try:
            r = _session().get(url, timeout=timeout)
            if r.status_code == 200:
                return r.content
            last = f"status {r.status_code}"
            if r.status_code == 404:
                break
        except requests.RequestException as e:
            last = str(e)
    raise RuntimeError(f"GET {url}: {last}")


# --- filters ---

def _mean_line_len(text):
    lines = text.splitlines() or [""]
    return sum(len(l) for l in lines) / len(lines)


def _has_autogen_marker(text):
    head = text[:2000].lower()
    return any(m in head for m in AUTOGEN_MARKERS)


def _size_ok(family, text):
    n = len(text.encode("utf-8", errors="ignore"))
    return MIN_DOC_BYTES[family] <= n <= MAX_DOC_BYTES[family]


def accept_py(text):
    if _has_autogen_marker(text) or _mean_line_len(text) > MEAN_LINE_CAP["py"]:
        return False
    try:
        ast.parse(text)
        return True
    except (SyntaxError, ValueError, RecursionError, MemoryError):
        return False


def accept_js(text):
    low = text[:4000].lower()
    if _has_autogen_marker(text) or any(m in low for m in JS_BUNDLE_MARKERS):
        return False
    if _mean_line_len(text) > MEAN_LINE_CAP["js"]:
        return False
    return any(k in text for k in JS_KEYWORDS)


def accept_html(text):
    low = text[:4000].lower()
    if not any(m in low for m in HTML_MARKERS):
        return False
    if _mean_line_len(text) > MEAN_LINE_CAP["html"]:
        return False
    return "data:image" not in low or text.count("data:image") * 1000 < len(text)


def accept_css(text):
    if "{" not in text or ":" not in text or "sourcemappingurl" in text[-500:].lower():
        return False
    if text.count("\n") < len(text) / MEAN_LINE_CAP["css"]:
        return False
    return not _has_autogen_marker(text)


ACCEPT = {"py": accept_py, "js": accept_js, "html": accept_html, "css": accept_css}


# --- dedup ---

def _simhash64(text):
    words = text.split()
    if len(words) < 4:
        words += [""] * (4 - len(words))
    v = [0] * 64
    for i in range(len(words) - 3):
        h = int.from_bytes(hashlib.blake2b(" ".join(words[i:i + 4]).encode("utf-8", "ignore"),
                                           digest_size=8).digest(), "big")
        for b in range(64):
            v[b] += 1 if (h >> b) & 1 else -1
    return sum(1 << b for b in range(64) if v[b] > 0)


class Deduper:
    """Exact sha1 dedup plus simhash near-dedup with banded LSH candidates."""

    def __init__(self):
        self.exact = set()
        self.bands = [{} for _ in range(SIMHASH_BANDS)]

    def is_dup(self, text):
        key = hashlib.sha1(text.encode("utf-8", "ignore")).digest()
        if key in self.exact:
            return True
        sh = _simhash64(text)
        width = 64 // SIMHASH_BANDS
        cands = set()
        for i in range(SIMHASH_BANDS):
            frag = (sh >> (i * width)) & ((1 << width) - 1)
            cands.update(self.bands[i].get(frag, ()))
        for c in cands:
            if bin(sh ^ c).count("1") <= SIMHASH_HAMMING:
                return True
        self.exact.add(key)
        for i in range(SIMHASH_BANDS):
            frag = (sh >> (i * width)) & ((1 << width) - 1)
            self.bands[i].setdefault(frag, []).append(sh)
        return False


# --- staging ---

def _staging_path(staging_dir, family):
    return os.path.join(staging_dir, family + ".jsonl")


def _record_source(staging_dir, key, meta):
    path = os.path.join(staging_dir, "sources.json")
    data = {}
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    data[key] = meta
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, sort_keys=True)


def _fetch_blob(blob_id):
    raw = _http_get(SWH_URL.format(blob_id=blob_id))
    return gzip.decompress(raw).decode("utf-8", errors="strict")


def stage_stack_edu(family, target_mb, staging_dir):
    from datasets import load_dataset
    os.makedirs(staging_dir, exist_ok=True)
    ds = load_dataset(STACK_EDU_ID, name=STACK_EDU_CONFIGS[family],
                      revision=STACK_EDU_REVISION, streaming=True, split="train")
    target = target_mb * 1024 * 1024
    written = kept = seen = 0
    out_path = _staging_path(staging_dir, family)
    with open(out_path, "w", encoding="utf-8") as out, \
         ThreadPoolExecutor(max_workers=SWH_WORKERS) as pool:
        pending = {}
        rows = iter(ds)

        def submit_next():
            nonlocal seen
            for row in rows:
                seen += 1
                if row.get("int_score", 0) < STAGE_MIN_SCORE:
                    continue
                n = row.get("length_bytes") or 0
                if not (MIN_DOC_BYTES[family] <= n <= MAX_DOC_BYTES[family]):
                    continue
                fut = pool.submit(_fetch_blob, row["blob_id"])
                pending[fut] = row["int_score"]
                return True
            return False

        for _ in range(SWH_WORKERS * 2):
            if not submit_next():
                break
        while pending and written < target:
            done = next(as_completed(pending))
            score = pending.pop(done)
            submit_next()
            try:
                text = done.result()
            except (RuntimeError, UnicodeDecodeError, OSError, gzip.BadGzipFile):
                continue
            line = json.dumps({"text": text, "score": score}, ensure_ascii=False)
            out.write(line + "\n")
            written += len(text.encode("utf-8"))
            kept += 1
            if kept % 2000 == 0:
                print(f"{family}: staged {kept} docs, {written/1e6:.0f} MB "
                      f"(scanned {seen})", flush=True)
        for fut in pending:
            fut.cancel()
    _record_source(staging_dir, family,
                   {"dataset": STACK_EDU_ID, "revision": STACK_EDU_REVISION,
                    "config": STACK_EDU_CONFIGS[family], "docs": kept, "bytes": written})
    print(f"{family}: DONE {kept} docs, {written/1e6:.1f} MB -> {out_path}", flush=True)


def stage_repos(staging_dir):
    os.makedirs(staging_dir, exist_ok=True)
    # long-lived handle: staging writers stay open across every repo below, closed once at the end.
    outs = {"html": open(_staging_path(staging_dir, "html"), "w", encoding="utf-8"),   # noqa: SIM115
            "css":  open(_staging_path(staging_dir, "css"), "w", encoding="utf-8")}   # noqa: SIM115
    totals = {"html": 0, "css": 0}
    tarball_hashes = {}
    for repo, ref in REPOS:
        try:
            blob = _http_get(CODELOAD_URL.format(repo=repo, ref=ref), timeout=600)
        except RuntimeError as e:
            print(f"repo SKIP {repo}@{ref}: {e}", flush=True)
            continue
        tarball_hashes[f"{repo}@{ref}"] = hashlib.sha256(blob).hexdigest()
        cap = REPO_BYTE_CAPS.get(repo)
        taken = 0
        members = []
        with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tf:
            for m in tf.getmembers():
                low = m.name.lower()
                fam = "html" if low.endswith((".html", ".htm")) else \
                      "css" if low.endswith(".css") else None
                if fam and m.isfile() and MIN_DOC_BYTES[fam] <= m.size <= MAX_DOC_BYTES[fam]:
                    members.append((m.name, fam, m))
            members.sort(key=lambda t: t[0])
            for _, fam, m in members:
                if cap is not None and taken >= cap:
                    break
                try:
                    text = tf.extractfile(m).read().decode("utf-8", errors="strict")
                except (UnicodeDecodeError, OSError):
                    continue
                outs[fam].write(json.dumps({"text": text, "score": None,
                                            "repo": repo}, ensure_ascii=False) + "\n")
                totals[fam] += len(text.encode("utf-8"))
                taken += m.size
        print(f"repo {repo}@{ref}: html {totals['html']/1e6:.0f} MB cum, "
              f"css {totals['css']/1e6:.0f} MB cum", flush=True)
    for f in outs.values():
        f.close()
    _record_source(staging_dir, "web",
                   {"repos": tarball_hashes, "html_bytes": totals["html"],
                    "css_bytes": totals["css"]})
    print(f"web: DONE html {totals['html']/1e6:.1f} MB, css {totals['css']/1e6:.1f} MB",
          flush=True)


def stage_qa(target_mb, staging_dir):
    from datasets import load_dataset
    os.makedirs(staging_dir, exist_ok=True)
    ds = load_dataset(QA_ID, revision=QA_REVISION, streaming=True, split="train")
    target = target_mb * 1024 * 1024
    written = kept = seen = 0
    out_path = _staging_path(staging_dir, "qa")
    with open(out_path, "w", encoding="utf-8") as out:
        for row in ds:
            seen += 1
            if written >= target:
                break
            if (row.get("SOURCE") or "") not in QA_SOURCES:
                continue
            meta = row.get("METADATA") or {}
            if isinstance(meta, str):
                try:
                    meta = json.loads(meta)
                except json.JSONDecodeError:
                    continue
            tags = {t.strip() for t in (meta.get("tags") or "").split(",")}
            if not tags & QA_TAGS:
                continue
            try:
                a_score = int(meta.get("answer_score") or 0)
                q_score = int(meta.get("question_score") or 0)
            except (TypeError, ValueError):
                continue
            if a_score < QA_MIN_ANSWER_SCORE or q_score < QA_MIN_QUESTION_SCORE:
                continue
            q = (row.get("INSTRUCTION") or "").strip()
            a = (row.get("RESPONSE") or "").strip()
            if not (QA_MIN_CHARS <= len(q) <= QA_MAX_CHARS and
                    QA_MIN_CHARS <= len(a) <= QA_MAX_CHARS):
                continue
            out.write(json.dumps({"q": q, "a": a, "score": a_score},
                                 ensure_ascii=False) + "\n")
            written += len(q) + len(a)
            kept += 1
            if kept % 5000 == 0:
                print(f"qa: staged {kept} pairs, {written/1e6:.0f} MB "
                      f"(scanned {seen})", flush=True)
    _record_source(staging_dir, "qa",
                   {"dataset": QA_ID, "revision": QA_REVISION, "pairs": kept,
                    "bytes": written})
    print(f"qa: DONE {kept} pairs, {written/1e6:.1f} MB -> {out_path}", flush=True)


# --- build ---

def _load_docs(staging_dir, family):
    path = _staging_path(staging_dir, family)
    docs = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            docs.append(json.loads(line))
    return docs


def _load_textbook_docs():
    docs = []
    for fname in sorted(os.listdir(TEXTBOOK_CACHE)):
        if not fname.endswith(".jsonl"):
            continue
        with open(os.path.join(TEXTBOOK_CACHE, fname), encoding="utf-8") as f:
            for line in f:
                docs.append(json.loads(line))
    return docs


def _wrap_qa(q, a):
    return (f"{IM_START}user\n{q}{IM_END}\n"
            f"{IM_START}assistant\n{a}{IM_END}\n{EOT}\n")


def _frame(family, doc):
    if family == "qa":
        return _wrap_qa(doc["q"], doc["a"])
    return doc["text"] + "\n" + EOT + "\n"


def _is_val(text):
    return int(hashlib.sha1(text.encode("utf-8", "ignore")).hexdigest()[:8], 16) \
        % VAL_BUCKETS == 0


def _filter_pool(docs, family, min_score, full_filters):
    dedup = Deduper()
    out = []
    for d in docs:
        text = d["text"] if family != "qa" else d["q"] + "\n" + d["a"]
        if family != "qa":
            if not _size_ok(family, text):
                continue
            if full_filters:
                if d.get("score") is not None and d["score"] < min_score:
                    continue
                if not ACCEPT[family](text):
                    continue
        if dedup.is_dup(text):
            continue
        out.append(d)
    return out


def _assemble(framed_docs, target_bytes):
    out, written = [], 0
    for chunk in framed_docs:
        if written >= target_bytes:
            break
        b = chunk.encode("utf-8")
        out.append(b)
        written += len(b)
    return b"".join(out)


def _split_and_assemble(family_docs_pairs, target_bytes, val_ratio, seed):
    """family_docs_pairs: list of (family, docs, weight). Returns train, val bytes."""
    rng = random.Random(seed)
    train_pools, val_pools, weights = [], [], []
    for family, docs, w in family_docs_pairs:
        tr, va = [], []
        for d in docs:
            key = d["text"] if family != "qa" else d["q"] + "\n" + d["a"]
            (va if _is_val(key) else tr).append(_frame(family, d))
        rng.shuffle(tr)
        rng.shuffle(va)
        train_pools.append(tr)
        val_pools.append(va)
        weights.append(w)

    def draw(pools, target):
        ws = list(weights)
        out, written = [], 0
        while written < target and any(pools):
            live = [i for i, p in enumerate(pools) if p]
            if len(live) < len([w for w in ws if w > 0]):
                for i in range(len(ws)):
                    if not pools[i] and ws[i] > 0:
                        print(f"pool {i} exhausted at {written/1e6:.0f} MB", flush=True)
                        ws[i] = 0.0
                if not any(ws):
                    break
            i = rng.choices(range(len(pools)), weights=ws)[0]
            if not pools[i]:
                ws[i] = 0.0
                continue
            b = pools[i].pop().encode("utf-8")
            out.append(b)
            written += len(b)
        return b"".join(out)

    val_target = int(target_bytes * val_ratio)
    return draw(train_pools, target_bytes - val_target), draw(val_pools, val_target)


def build(family, staging_dir, out_train, out_val, target_mb, val_ratio, seed, min_score):
    target = target_mb * 1024 * 1024
    if family in CODE_FAMILIES or family == "qa":
        docs = _filter_pool(_load_docs(staging_dir, family), family, min_score, True)
        pairs = [(family, docs, 1.0)]
    elif family == "textbook":
        by_lang = {}
        for d in _load_textbook_docs():
            by_lang.setdefault(d["lang"], []).append(d)
        pairs = [(lang, _filter_pool(docs, lang, 0, True),
                  float(sum(len(d["text"]) for d in docs)))
                 for lang, docs in sorted(by_lang.items())]
    elif family in MIXED_VARIANTS:
        full = family != "mixed_raw"
        score = BUILD_MIN_SCORE if family == "mixed_edu" else STAGE_MIN_SCORE
        pairs = [(f, _filter_pool(_load_docs(staging_dir, f), f, score, full),
                  MIXED_WEIGHTS[f]) for f in CODE_FAMILIES]
        if family == "mixed_qa":
            pairs = [(f, d, w * (1.0 - MIXED_QA_SHARE)) for f, d, w in pairs]
            qa_docs = _filter_pool(_load_docs(staging_dir, "qa"), "qa", 0, True)
            pairs.append(("qa", qa_docs, MIXED_QA_SHARE))
    else:
        raise ValueError(f"unknown family: {family}")

    train, val = _split_and_assemble(pairs, target, val_ratio, seed)
    os.makedirs(os.path.dirname(os.path.abspath(out_train)) or ".", exist_ok=True)
    with open(out_train, "wb") as f:
        f.write(train)
    with open(out_val, "wb") as f:
        f.write(val)
    short = len(train) < (target - int(target * val_ratio)) * 0.98
    print(f"{family}: train {len(train)/1e6:.1f} MB, val {len(val)/1e6:.1f} MB"
          + ("  WARNING: pool underran target" if short else ""), flush=True)
    return {"train_bytes": len(train), "val_bytes": len(val), "underran": short}


def main(argv=None):
    ap = argparse.ArgumentParser(description="Build the code byte-level corpora.")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("stage", help="pull source docs into the staging cache")
    sp.add_argument("--family", required=True, choices=("py", "js", "web", "qa"))
    sp.add_argument("--target-mb", type=int, default=1300)
    sp.add_argument("--staging-dir", default=DEFAULT_STAGING)

    bp = sub.add_parser("build", help="assemble bins from the staging cache")
    bp.add_argument("--family", required=True,
                    choices=(*CODE_FAMILIES, "qa", "textbook", *MIXED_VARIANTS))
    bp.add_argument("--staging-dir", default=DEFAULT_STAGING)
    bp.add_argument("--out-train", required=True)
    bp.add_argument("--out-val", required=True)
    bp.add_argument("--target-mb", type=int, required=True)
    bp.add_argument("--val-ratio", type=float, default=0.02)
    bp.add_argument("--seed", type=int, default=DEFAULT_SEED)
    bp.add_argument("--min-score", type=int, default=BUILD_MIN_SCORE)

    args = ap.parse_args(argv)
    if args.cmd == "stage":
        if args.family == "web":
            stage_repos(args.staging_dir)
        elif args.family == "qa":
            stage_qa(args.target_mb, args.staging_dir)
        else:
            stage_stack_edu(args.family, args.target_mb, args.staging_dir)
    else:
        build(args.family, args.staging_dir, args.out_train, args.out_val,
              args.target_mb, args.val_ratio, args.seed, args.min_score)


if __name__ == "__main__":
    sys.exit(main())
