# ------------------------------------------------------------------------------------
# Developed by Carpathian, LLC.
# ------------------------------------------------------------------------------------
# Legal Notice: Distribution Not Authorized.
# ------------------------------------------------------------------------------------
# Notes:
# - EAGLE-3 draft head. Source: arXiv 2503.01840.
# - Architecture: a SINGLE transformer decoder block plus two FC adapters
#   that read the TARGET model's hidden states at three depth slices
#   (low, middle, high — typically layers L/4, L/2, 3L/4). Predicts the
#   next-byte distribution directly (not next-layer features as in
#   EAGLE-1).
# - Reuses the target's byte-0 head via byte0_projector() (frozen). Total
#   draft params ≈ 3% of target. Published 4-6.5× speedup on BPE models.
#   Predicted 3-4× on byte-level.
# - Model-agnostic (preflight rule 11a). All variant-specific output
#   projection lives in byte0_projector(); this module never inspects
#   model attributes for output dispatch.
# - Training: pure self-distillation against the target's argmax (soft-CE
#   over the target's full distribution). ~250M target-generated bytes.
#   Lives in a separate dispatch.
# veritate_mri/decode/eagle3.py
# ------------------------------------------------------------------------------------
# Imports:

from typing import List, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

# ------------------------------------------------------------------------------------
# Constants

DEFAULT_TAP_FRACS = (0.25, 0.5, 0.75)   # layers L/4, L/2, 3L/4

# ------------------------------------------------------------------------------------
# Functions


class _Eagle3DecoderBlock(nn.Module):
    """One transformer-style block used by the draft head. Lightweight
    (single block; ~10-30M params depending on target hidden size)."""

    def __init__(self, hidden: int, n_heads: int, ffn: int):
        super().__init__()
        self.n1   = nn.LayerNorm(hidden)
        self.qkv  = nn.Linear(hidden, 3 * hidden, bias=False)
        self.proj = nn.Linear(hidden, hidden, bias=False)
        self.n2   = nn.LayerNorm(hidden)
        self.fc_up   = nn.Linear(hidden, ffn, bias=False)
        self.fc_down = nn.Linear(ffn, hidden, bias=False)
        self.n_heads = n_heads
        self.head_dim = hidden // n_heads
        assert hidden % n_heads == 0, "hidden must be divisible by n_heads"

    def forward(self, x):
        # x: [B, T, hidden]
        B, T, C = x.shape
        h = self.n1(x)
        qkv = self.qkv(h).view(B, T, 3, self.n_heads, self.head_dim).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]
        out = F.scaled_dot_product_attention(q, k, v, is_causal=True)
        out = out.transpose(1, 2).contiguous().view(B, T, C)
        x = x + self.proj(out)
        x = x + self.fc_down(F.gelu(self.fc_up(self.n2(x))))
        return x


class Eagle3DraftHead(nn.Module):
    """The EAGLE-3 draft. Consumes [low, mid, high] hidden states + the
    most recent emitted token's embedding. Outputs next-byte logits.
    """

    def __init__(self, hidden: int, n_heads: int, ffn: int, vocab: int):
        super().__init__()
        self.hidden = hidden
        self.vocab  = vocab
        # Fuse the three target hidden states (3 * hidden) -> hidden
        self.fc_fuse = nn.Linear(3 * hidden, hidden, bias=False)
        # Fuse fused-hidden + token-embed -> hidden
        self.fc_in   = nn.Linear(2 * hidden, hidden, bias=False)
        # One decoder block
        self.block = _Eagle3DecoderBlock(hidden, n_heads, ffn)
        # Token embedder (shared with target's tok_emb at runtime — set
        # externally to avoid double-storage)
        self.tok_emb = None
        # The LM head is the TARGET's tied LM head (set externally + frozen)
        self.lm_head = None

    def set_tied_modules(self, tok_emb: nn.Module, lm_head_callable):
        """Wire the target's embedding + LM head (frozen) into the draft.
        `lm_head_callable(residual) -> logits` — for canonical / VeritateRoPE
        this is `lambda r: target.lm_head(target.n_out(r))`; for Veritate800M
        it's the byte-0 MTP-head pipeline."""
        self.tok_emb = tok_emb
        self.lm_head = lm_head_callable

    def forward(self, low_h, mid_h, high_h, token_ids):
        """
        low_h, mid_h, high_h: [B, T, hidden] target hidden states at the tap layers
        token_ids:           [B, T] long — the input tokens
        Returns: [B, T, vocab] logits — predicted next-byte distributions.
        """
        if self.tok_emb is None or self.lm_head is None:
            raise RuntimeError("Eagle3DraftHead.set_tied_modules() must be called first.")
        g = self.fc_fuse(torch.cat([low_h, mid_h, high_h], dim=-1))   # [B, T, hidden]
        e = self.tok_emb(token_ids)                                    # [B, T, hidden]
        a = self.fc_in(torch.cat([g, e], dim=-1))                      # [B, T, hidden]
        h = self.block(a)                                              # [B, T, hidden]
        # Project through target's tied LM head (callable handles n_out + lm_head)
        logits = self.lm_head(h)                                       # [B, T, vocab]
        return logits

    def param_count(self) -> int:
        own = sum(p.numel() for p in self.parameters()
                  if p is not self.tok_emb.weight)  # don't count shared
        return own


def attach_target_taps(target_model, draft_head: Eagle3DraftHead,
                       tap_fracs=DEFAULT_TAP_FRACS):
    """Wire the target model so its hidden states at the three tap layers
    are captured per-forward. Returns a (cleanup_fn, capture_dict) tuple.
    The capture_dict gets populated with keys 'low', 'mid', 'high' as the
    target runs forward. The cleanup_fn detaches the hooks.
    """
    L = target_model.layers
    tap_layers = [max(0, min(L - 1, int(round(L * f)))) for f in tap_fracs]
    captures = {}
    handles = []

    def make_hook(name):
        def h(_m, _i, output):
            captures[name] = output.detach()
        return h

    names = ("low", "mid", "high")
    for tap_name, layer_idx in zip(names, tap_layers):
        handle = target_model.blocks[layer_idx].register_forward_hook(make_hook(tap_name))
        handles.append(handle)

    def cleanup():
        for h in handles:
            h.remove()

    return cleanup, captures, tap_layers


def build_eagle3_for_target(target_model, n_heads: Optional[int] = None,
                            ffn: Optional[int] = None) -> Eagle3DraftHead:
    """Construct an EAGLE-3 head sized to match `target_model`. Defaults:
    n_heads = target.heads, ffn = 4 * hidden (typical transformer block).
    Output dispatch is delegated to byte0_projector() — adding a new
    target variant requires zero changes here, only an entry in
    byte0_projector() (or a `project_byte0` method on the new model)."""
    from . import byte0_projector
    hidden = target_model.hidden
    if n_heads is None:
        n_heads = target_model.heads
    if ffn is None:
        ffn = 4 * hidden
    vocab = target_model.vocab
    head = Eagle3DraftHead(hidden=hidden, n_heads=n_heads, ffn=ffn, vocab=vocab)
    project_fn = byte0_projector(target_model)
    head.set_tied_modules(target_model.tok_emb, project_fn)
    return head
