# ------------------------------------------------------------------------------------
# Developed by Carpathian, LLC.
# ------------------------------------------------------------------------------------
# Legal Notice: Distribution Not Authorized.
# ------------------------------------------------------------------------------------
# Notes:
# - Kangaroo self-speculative draft. Reuses the target model's first L/4
#   blocks (frozen) + the tied LM head as the "draft" trunk, plus a small
#   trainable adapter MLP that bridges the early-layer residual to a
#   distribution close to the target's final output.
# - Source: arXiv 2404.18911 ("Kangaroo: Lossless Self-Speculative Decoding
#   via Double Early Exiting"). Published 2.04× speedup on Llama-7B with
#   88.7% fewer added params than Medusa-1.
# - Veritate-byte fit: with target=800M (L=28, hidden=1536), the draft is
#   the first 7 blocks (200M frozen) + a ~5M adapter MLP + the tied LM head.
#   Trained offline against the frozen target's outputs over ~24h of self-
#   generated bytes; then used as the draft in speculative-decode loops.
# - This module ONLY defines the architecture. Training lives in
#   experiments/v2/kangaroo/train.py (separate dispatch). Inference wiring
#   into Brain.stream_fast as mode='kangaroo' lands once a trained adapter
#   ckpt exists.
# veritate_mri/decode/kangaroo.py
# ------------------------------------------------------------------------------------
# Imports:

from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

# ------------------------------------------------------------------------------------
# Constants

# ------------------------------------------------------------------------------------
# Functions


class KangarooAdapter(nn.Module):
    """A small MLP that bridges the residual at layer L/4 to a representation
    the LM head can read. Two linear layers + a residual + a final norm.
    Total params ≈ 2 * hidden^2 + 2*hidden — for 800M's hidden=1536 that's
    ~4.7M params (0.59% of target).
    """

    def __init__(self, hidden: int, expansion: int = 2, dropout: float = 0.0):
        super().__init__()
        self.hidden    = hidden
        self.expansion = expansion
        self.fc1 = nn.Linear(hidden, hidden * expansion, bias=False)
        self.fc2 = nn.Linear(hidden * expansion, hidden, bias=False)
        self.norm = nn.LayerNorm(hidden)
        self.dropout = nn.Dropout(dropout) if dropout > 0 else nn.Identity()

    def forward(self, x):
        # Two-layer MLP with GELU. Output is residual-added + normed so it
        # produces "trunk-final-shape" hidden states.
        h = self.fc2(self.dropout(F.gelu(self.fc1(x))))
        return self.norm(x + h)

    def param_count(self) -> int:
        return sum(p.numel() for p in self.parameters())


class KangarooDraft:
    """Wraps a FROZEN target Veritate/800M model + a trained Kangaroo adapter.
    Acts as a "small drafter" for speculative decoding: forwards through the
    target's first L_exit blocks, applies the adapter, then projects through
    the target's tied LM head.

    The math: the adapter learns p_adapter(byte_t | x_<t) ≈ p_target(byte_t | x_<t)
    using only the first L_exit blocks. If the adapter is good, the
    speculator's drafts are accepted at high rate during verify.

    Veritate-fit specifics:
      - Target's LM head varies: canonical Veritate uses `lm_head` tied to
        `tok_emb`; Veritate800M routes through `mtp.lm_head` (also tied).
        We call .project(residual) which dispatches correctly.
    """

    def __init__(self, target_model, adapter: KangarooAdapter,
                 exit_layer_frac: float = 0.25):
        self.model   = target_model
        self.adapter = adapter
        # Exit after this many blocks (so layer indices 0..exit_layer-1 run).
        self.exit_layer = max(1, int(round(target_model.layers * exit_layer_frac)))
        self._is_rope = hasattr(target_model, "rope_cos") and hasattr(target_model, "rope_sin")
        self._is_800m = self._is_rope and hasattr(target_model, "mtp")

    def _project(self, residual_last_pos):
        """Apply the target's final-output projection. Last position only.
        residual_last_pos: [hidden]"""
        x = self.model.n_out(residual_last_pos)
        if self._is_800m:
            head0 = self.model.mtp.norms[0](self.model.mtp.transforms[0](x))
            return self.model.mtp.lm_head(head0)
        return self.model.lm_head(x)

    @torch.no_grad()
    def draft_one(self, tokens: torch.Tensor) -> torch.Tensor:
        """Forward through the first L_exit blocks + adapter + project.
        tokens: [B, T] long. Returns logits at the last position: [B, vocab]."""
        m = self.model
        if self._is_rope:
            if tokens.size(1) > m.rope_cos.size(0):
                m.extend_rope(tokens.size(1))
            x = m.embed(tokens)
        else:
            T = tokens.size(1)
            positions = torch.arange(T, device=tokens.device).unsqueeze(0)
            x = m.tok_emb(tokens) + m.pos_emb(positions)

        for L in range(self.exit_layer):
            blk = m.blocks[L]
            if self._is_rope:
                x = blk(x, m.rope_cos, m.rope_sin)
            else:
                x = blk(x)

        # Adapter on the last position only — cheaper than running over the
        # full sequence.
        last = x[:, -1, :]                # [B, hidden]
        bridged = self.adapter(last)      # [B, hidden]
        logits = self._project(bridged)   # [B, vocab]
        return logits

    def param_count(self) -> int:
        return self.adapter.param_count()
